version: '3.3'

services:
  bot:
    build: .
    container_name: vk_calendar_bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    env_file:
      - .env
    volumes:
      - ./calendar:/app/calendar
      - ./data:/app/data