version: '3.3'

services:
  bot:
    build: .
    container_name: telegram_calendar_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./calendar:/app/calendar
      - ./session.session:/app/session.session